[Countries]

	[Countries.CA]
	deathbygun = 2.38
	guns = 23.8 
	rank = 12
	from = 19
	to = 1073

	[Countries.US]
	deathbygun = 10.3
	guns = 100.0
	rank = 1
	from = 1073
	to = 2127

	[Countries.UK]
	deathbygun = 0.25
	guns = 6.7 
	rank = 22
	from = 2127
	to = 3181
